# Generated by Django 2.2.2 on 2019-08-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organic_fair', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organicfaircontact',
            name='phone',
        ),
        migrations.AddField(
            model_name='organicfaircontact',
            name='phone',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.Phone', verbose_name='Telefone'),
        ),
        migrations.RemoveField(
            model_name='organicfaircontact',
            name='social_network',
        ),
        migrations.AddField(
            model_name='organicfaircontact',
            name='social_network',
            field=models.ManyToManyField(blank=True, null=True, to='contacts.SocialNetwork', verbose_name='Rede Social'),
        ),
    ]
