# Generated by Django 2.2.2 on 2019-08-21 23:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic_farmer', '0002_auto_20190820_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter')], max_length=30, verbose_name='Nome da Rede Social')),
                ('link', models.CharField(max_length=50, null=True, verbose_name='Link da Rede Social')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': 'Redes Sociais',
            },
        ),
        migrations.RemoveField(
            model_name='organicfarmercontact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organicfarmercontact',
            name='social_network',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='contact',
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='biograph',
            field=models.CharField(blank=True, max_length=255, verbose_name='Biografia'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='cel_phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='city',
            field=models.CharField(blank=True, max_length=165, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='complement',
            field=models.CharField(blank=True, max_length=255, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='country',
            field=models.CharField(blank=True, choices=[('BR', 'Brasil')], max_length=40, null=True, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('CERTIFICADORA', 'Certificadora'), ('OPAC', 'Organismo Participativo de Avaliação da Conformidade'), ('OCS', 'Organizações de Controle Social')], max_length=50, unique=True, verbose_name='Tipo de Entidade'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Geolocalização'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='locality',
            field=models.CharField(blank=True, max_length=255, verbose_name='Localidade'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='site',
            field=models.CharField(blank=True, max_length=50, verbose_name='Site'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='state',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=165, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='street_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='organicfarmer',
            name='entity',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Entidade'),
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
        migrations.DeleteModel(
            name='EntityType',
        ),
        migrations.DeleteModel(
            name='OrganicFarmerAddress',
        ),
        migrations.DeleteModel(
            name='OrganicFarmerContact',
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='social_network',
            field=models.ManyToManyField(blank=True, to='organic_farmer.SocialNetwork', verbose_name='Rede Social'),
        ),
    ]
