# Generated by Django 2.2.2 on 2019-08-25 20:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organic_farmer', '0003_auto_20190821_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Entidade')),
            ],
            options={
                'verbose_name': 'Entidade',
                'verbose_name_plural': 'Entidades',
            },
        ),
        migrations.CreateModel(
            name='EntityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('CERTIFICADORA', 'Certificadora'), ('OPAC', 'Organismo Participativo de Avaliação da Conformidade'), ('OCS', 'Organizações de Controle Social')], max_length=50, unique=True, verbose_name='Tipo de Entidade')),
            ],
            options={
                'verbose_name': 'Tipo de Entidade',
                'verbose_name_plural': 'Tipos de Entidade',
            },
        ),
        migrations.CreateModel(
            name='OrganicFarmerAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality', models.CharField(blank=True, max_length=255, verbose_name='Localidade')),
                ('street_number', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complement', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('neighborhood', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('postal_code', models.CharField(blank=True, max_length=8, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=165, null=True, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=165, null=True, verbose_name='Estado')),
                ('country', models.CharField(blank=True, choices=[('BR', 'Brasil')], max_length=40, null=True, verbose_name='País')),
                ('geolocation', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
                'ordering': ['locality', 'street_number', 'neighborhood', 'city', 'state', 'country'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganicFarmerContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('site', models.CharField(blank=True, max_length=50, verbose_name='Site')),
                ('phone', models.ManyToManyField(blank=True, to='contacts.Phone', verbose_name='Telefone')),
                ('social_network', models.ManyToManyField(blank=True, to='contacts.SocialNetwork', verbose_name='Rede Social')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='biograph',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='cel_phone',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='entity_type',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='geolocation',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='site',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='social_network',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='organicfarmer',
            name='street_number',
        ),
        migrations.AlterField(
            model_name='organicfarmer',
            name='entity',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='organic_farmer.Entity', verbose_name='Entidade'),
        ),
        migrations.DeleteModel(
            name='SocialNetwork',
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='organic_farmer.EntityType', verbose_name='Tipo de Entidade'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endereco', to='organic_farmer.OrganicFarmerAddress', verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='organicfarmer',
            name='contact',
            field=models.ForeignKey(null=True, on_delete='CASCADE', to='organic_farmer.OrganicFarmerContact', verbose_name='Contatos'),
        ),
    ]
