# Generated by Django 2.2.6 on 2019-12-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic_farmer', '0005_auto_20191203_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicfarmer',
            name='cnpo_register',
            field=models.CharField(max_length=20, unique=True, verbose_name='Registro CNPO'),
        ),
    ]
