# Generated by Django 2.2.6 on 2019-12-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organic_farmer', '0006_auto_20191207_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organicfarmer',
            name='fantasy_name',
        ),
    ]
