# Generated by Django 2.2.6 on 2019-12-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic_farmer', '0007_remove_organicfarmer_fantasy_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organicfarmer',
            name='cnpo_register',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Registro CNPO'),
        ),
    ]
