# Generated by Django 2.2.6 on 2019-12-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic_farmer', '0008_auto_20191217_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Atividade'),
        ),
    ]
