# Generated by Django 2.2.6 on 2019-12-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic_farmer', '0009_auto_20191218_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Entidade'),
        ),
        migrations.AlterField(
            model_name='organicfarmer',
            name='cnpo_register',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Registro CNPO'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Escopo'),
        ),
    ]
