# Generated by Django 2.2.6 on 2019-12-19 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organic_farmer', '0010_auto_20191219_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='CNPOFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Nome do Arquivo')),
                ('cnpo_file', models.FileField(upload_to='cnpo_files', verbose_name='Arquivo CNPO')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
            ],
            options={
                'verbose_name': 'Arquivo CNPO',
                'verbose_name_plural': 'Arquivos CNPO',
            },
        ),
    ]
